# Generated by Django 4.0.6 on 2022-07-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredassets',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
